GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6a0faff2a1960a73529396b1

###

DELETE http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040-243563",
  "name": "Liisa Marttinen"
}