GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6a0fad4c20d2ff78d10a052b

###

DELETE http://localhost:3001/api/persons/6a0fb06ca1960a73529396b2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040-243563",
  "name": "Liisa Marttinen"
}